#!/bin/bash

rm "./abi.json"
rm "./proof.json"
rm "./label_heterogenity_proof.json"
rm "./label_heterogenitytrainer0_proof.json"
rm "./label_heterogenitytrainer1_proof.json"
rm "./label_heterogenitytrainer2_proof.json"
rm "./label_heterogenitytrainer3_proof.json"
rm "./label_heterogenitytrainer4_proof.json"
rm "./label_heterogenitytrainer5_proof.json"
rm "./label_heterogenitytrainer6_proof.json"
rm "./label_heterogenitytrainer7_proof.json"
rm "./label_heterogenitytrainer8_proof.json"
rm "./label_heterogenitytrainer9_proof.json"
rm "./proving.key"
rm "./label_heterogenity_proving.key"
rm "./label_heterogenity_verification.key"
rm "./verification.key"
rm "./verifier.sol"
rm "./witness"
rm "./label_heterogenity_witness"
rm "./out"
rm "./out.wtns"
rm "./out.r1cs"
rm "./label_heterogenity"
rm "./label_heterogenity.r1cs"